{{- if (include "featbit.postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "featbit.postgresql.secretName" . }}
  labels:
    {{- include "featbit-metadata-labels-common" . | nindent 4 }}
  annotations:
    {{- include "featbit-metadata-annotations-common" . | nindent 4 }}
type: Opaque
data:
  {{ template "featbit.postgresql.secretPasswordKey" . }}: {{ .Values.externalPostgresql.password | b64enc | quote }}
{{- end }}