# example of featbit pro configuration in exposing services via load balancer(auto discovery ips)
evaluationServerExternalUrl: ""
autoDiscovery: true

architecture:
  tier: "professional"
  database: "postgresql"

ui:
  service:
    type: LoadBalancer
    port: 80


api:
  service:
    type: LoadBalancer
    port: 80

els:
  service:
    type: LoadBalancer
    port: 80

kafka:
  enabled: true
clickhouse:
  enabled: true